### ISSUE TITLE
API not functional

### ISSUE THREAD

**Issue by bajoski34** [seyi-adeleke/Nigerian-states-api#10]
Hi @seyi-adeleke please note that there is an issue with the API. 

Please if you are using mlab for the application, please switch to mongodb Atlas as Heroku has discontinued the feature. 

Hope to hear from you soon. 

![image](https://user-images.githubusercontent.com/39011309/110912201-f13f3200-8313-11eb-9a7e-af615d77a229.png)

Best regards

**Comment by seyi-adeleke** [comment]
Hi @bajoski34, thanks for flagging, this has been resolved
