### ISSUE TITLE
Hitting a route that doesn't exist should return a well formatted error message

### ISSUE THREAD

**Issue by seyi-adeleke** [seyi-adeleke/Nigerian-states-api#4]
Currently, when a user tries to access an endpoint that doesn't exist the application returns an error. A  well formatted error message should be returned when such a situation occurs.

**Comment by seyi-adeleke** [comment]
@vynessa 😉

**Comment by vynessa** [comment]
@seyi-adeleke Great way to solve this. How about redirecting the user to the default URL `https://nigerian-states-info.herokuapp.com/`?

**Comment by seyi-adeleke** [comment]
@vynessa That can work for non api-routes but for any `/api/v1/*` where * isn't a valid endpoint it should return a 404
